<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="52" started-at="2017-03-28T23:57:57Z" finished-at="2017-03-28T23:57:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="52" started-at="2017-03-28T23:57:57Z" finished-at="2017-03-28T23:57:57Z">
      <class name="com.outware.test.LoginTest">
        <test-method status="FAIL" signature="testLoginFailure()[pri:0, instance:com.outware.test.LoginTest@47d384ee]" name="testLoginFailure" duration-ms="22" started-at="2017-03-29T10:57:57Z" finished-at="2017-03-29T10:57:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.outware.test.LoginTest.testLoginFailure(LoginTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginFailure -->
        <test-method status="PASS" signature="testLoginLocked()[pri:0, instance:com.outware.test.LoginTest@47d384ee]" name="testLoginLocked" duration-ms="2" started-at="2017-03-29T10:57:57Z" finished-at="2017-03-29T10:57:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginLocked -->
        <test-method status="PASS" signature="testLoginSuccess()[pri:0, instance:com.outware.test.LoginTest@47d384ee]" name="testLoginSuccess" duration-ms="0" started-at="2017-03-29T10:57:57Z" finished-at="2017-03-29T10:57:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginSuccess -->
      </class> <!-- com.outware.test.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
